apiVersion: v1
kind: Namespace
metadata:
  name: market-scanning
  labels:
    name: market-scanning
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: market-scanning-quota
  namespace: market-scanning
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: market-scanning-limits
  namespace: market-scanning
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container